{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-feasts
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/feasts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/feasts/feasts_{{ version }}.tar.gz
  sha256: a968cec39cd12b5bf5e76e815d2e9a54ed98ef1aa46e9d1acf62ef6517f38fa6

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr >=1.0.0
    - r-fabletools >=0.3.1
    - r-ggplot2 >=3.0.0
    - r-lifecycle
    - r-lubridate
    - r-rlang >=0.2.0
    - r-scales >=1.1.0
    - r-slider
    - r-tibble >=1.4.1
    - r-tidyr >=0.8.3
    - r-tsibble >=0.9.0
    - r-vctrs
    - r-gtable
  run:
    - r-base
    - r-dplyr >=1.0.0
    - r-fabletools >=0.3.1
    - r-ggplot2 >=3.0.0
    - r-lifecycle
    - r-lubridate
    - r-rlang >=0.2.0
    - r-scales >=1.1.0
    - r-slider
    - r-tibble >=1.4.1
    - r-tidyr >=0.8.3
    - r-tsibble >=0.9.0
    - r-vctrs
    - r-gtable

test:
  commands:
    - $R -e "library('feasts')"           # [not win]
    - "\"%R%\" -e \"library('feasts')\""  # [win]

about:
  home: http://feasts.tidyverts.org/, https://github.com/tidyverts/feasts/
  license: GPL-3.0-only
  summary: "Provides a collection of features, decomposition methods, statistical summaries and graphics functions for the analysing tidy time series data. The package name 'feasts' is an acronym comprising of its key features: Feature Extraction And Statistics for Time Series."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: feasts
# Title: Feature Extraction and Statistics for Time Series
# Version: 0.1.3
# Description: Provides a collection of features, decomposition methods, statistical summaries and graphics functions for the analysing tidy time series data. The package name 'feasts' is an acronym comprising of its key features: Feature Extraction And Statistics for Time Series.
# Authors@R: c( person("Mitchell", "O'Hara-Wild", email = "mail@mitchelloharawild.com", role = c("aut", "cre")), person("Rob", "Hyndman", role = "aut"), person("Earo", "Wang", role = "aut"), person("Di", "Cook", role = "ctb"), person("Thiyanga", "Talagala", role = "ctb", comment = "Correlation features"), person("Leanne", "Chhay", role = "ctb", comment = "Guerrero's method") )
# Depends: R (>= 3.5.0), fabletools (>= 0.1.2)
# Imports: rlang (>= 0.2.0), tibble (>= 1.4.1), tsibble (>= 0.8.0), ggplot2 (>= 3.0.0), dplyr (>= 0.8.0), tidyr (>= 0.8.3), scales (>= 1.1.0), vctrs, lubridate, grid, slider, utils
# Suggests: tsibbledata, pillar (>= 1.0.1), knitr, rmarkdown, testthat, covr, seasonal, urca, fracdiff, fable, ForeCA
# ByteCompile: true
# VignetteBuilder: knitr
# License: GPL-3
# URL: http://feasts.tidyverts.org/, https://github.com/tidyverts/feasts/
# BugReports: https://github.com/tidyverts/feasts/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.0.2.9000
# Language: en-GB
# NeedsCompilation: no
# Packaged: 2020-03-17 23:57:43 UTC; mitchell
# Author: Mitchell O'Hara-Wild [aut, cre], Rob Hyndman [aut], Earo Wang [aut], Di Cook [ctb], Thiyanga Talagala [ctb] (Correlation features), Leanne Chhay [ctb] (Guerrero's method)
# Maintainer: Mitchell O'Hara-Wild <mail@mitchelloharawild.com>
# Repository: CRAN
# Date/Publication: 2020-03-18 07:00:11 UTC
