appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: OXD51A/QLR+EV0j3vX1RrF8weod0pgm/f28W8opnKWzyCpCWC8Nn45kKKYCWCORncCCWeffznNDIS9q48SFmybIciYkmnl2aOoGuRfMGMg9cdMOemZSu/729030i4D3mrjcHlluMaJGrI8XC+x/uI87jUPiU331kWMuTVGNkIsGFS8cAznZzXdc9ZJQ3G+zTBv8+ptv2mbaSPkQk6/MNyf0wHJuZi1sfagptlF/4QsbyS/Y/j/cCq5K4VqaM/Sm21525DdVIXQiMzhGVXowM0VR04ltAdkucJCwX4Mtz2c2dXeBCxd6n5ny6uRYt4sL2FJCq4t/YAGfQJDwZ+pQJ6BnPwf0LxZdWK45cNhk8oFbdwuQAEtYeJOV9oKeRkFxPhr9MnDp0FO9xZ65lxJtj44FySgA0TFMuMJDejS7jYGCijxztAuAow70MpLFsz4nXIg80JSGNU2T4QHg+3MNNpoprMomTbEOtA4cgIMCr0yo83F4cRgAec7h3eV0bx5hFiyjpIwfgjCwJ8h4CghYbtQSF/UALTrmE9gPA1UchhGJld12oVylFkL9Z/J2gUbxDwFjSJ24JX32deddlmekbyDszgu9GbDjkFNczPC6ImjJoYkVuK+ZYYHFNy/jaXR6kiWJ3ZjqUcevk7lyaTunwPTijzzSmKNgWQbCcj/RN/G8=
